# $Id: Makefile,v 1.6 2003/04/09 23:53:39 fingolfin Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = multilingual.xml
#TARGET = index.php intro.php install.php upgrade.php packages.php conf.php usage.php header.inc
TARGET = index.php intro.php files.php header.inc
WANT_HTML = 1
DESTDIR = doc/multilingual

include $(basedir)/Makefile.common

# eof
