# $Id: Makefile,v 1.1 2004/03/04 02:17:05 alexkhansen Exp $

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = multilingual.xml
#TARGET = index.php intro.php install.php upgrade.php packages.php conf.php usage.php header.inc
TARGET = index.php intro.php files.php procedure.php resources.php header.inc
WANT_HTML = 1
DESTDIR = doc/multilingual

include $(basedir)/Makefile.common

# eof
